name: pa_mobile_tani_shop
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.3
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  smooth_star_rating_null_safety: ^1.0.4+2
  google_fonts: ^2.0.0 
  flutter_svg: ^0.22.0
  firebase_auth: ^3.3.19
  path: ^1.8.0
  image_picker: ^0.8.5+3
  firebase_storage: "^10.0.2"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Staatliches
      fonts:
        - asset: assets/font/Staatliches-Regular.ttf
    - family: Oxygen
      fonts:
        - asset: assets/font/Oxygen-Regular.ttf
    - family: Rubik
      fonts:
        - asset: assets/font/RubikMicrobe-Regular.ttf
    - family: Nanum
      fonts:
        - asset: assets/font/NanumMyeongjo-Regular.ttf
    - family: Pacifi
      fonts:
        - asset: assets/font/Pacifico-Regular.ttf
    - family: Quicksand
      fonts :
        - asset: assets/font/Quicksand-Regular.ttf
        - asset: assets/font/Quicksand-Light.ttf
          weight: 300
        - asset: assets/font/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/font/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/font/Quicksand-Bold.ttf
          weight: 700

